# Keep the style edition in sync with "edition" in Cargo.toml!
style_edition = "2024"

# https://github.com/rust-lang/rustfmt/blob/master/Configurations.md
# == These require the nightly channel ==
# format_code_in_doc_comments = true
# format_macro_matchers = true
# group_imports = "StdExternalCrate"
# imports_granularity = "Item"
# normalize_doc_attributes = true
# reorder_impl_items = true

use_field_init_shorthand = true
