[package]
name = "widget_scrolling"
version = "0.1.0"
edition = "2024"

[dependencies]
ratatui = { version = "0.30", default-features = false, features = ["crossterm", "unstable-rendered-line-info"] }
